version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    text:
      path: stdout
      colors: true
      print-issued-lines: true
      print-linter-name: true

linters:
  default: none
  enable:
    # Error‑handling & correctness
    - errcheck
    - govet
    - staticcheck
    - ineffassign

    # Style checks
    - revive
    - misspell
    - whitespace
    - wsl_v5

    # Complexity
    - gocyclo
    - gocognit
    - funlen

    # Security
    - gosec

    # Performance
    - prealloc

    # Maintainability
    - dupl
    - gocritic

    # Declaration & import‐order linters
    - importas
    - decorder
    - funcorder
    - gochecknoglobals
    - gochecknoinits

  exclusions:
    # … your existing exclusions …

  settings:
    # … all your existing linter settings, EXCEPT remove gci here …


formatters:
  enable:
    - goimports
    - golines
    - gci          # ← added here
  settings:
    goimports:
      local-prefixes: github.com/terrpan/polly

    gci:             # ← moved into formatters.settings
      sections:
        - standard
        - default
        - prefix(github.com/terrpan/polly)
        - blank
        - dot
      skip-generated: false
      custom-order: true


issues:
  max-issues-per-linter: 50
  max-same-issues: 10
