version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    text:
      path: stdout
      colors: true
      print-issued-lines: true
      print-linter-name: true

linters:
  default: none
  enable:
    # Error-handling & correctness
    - errcheck
    - govet
    - staticcheck
    - ineffassign

    # Style checks (linters)
    - revive
    - misspell
    - whitespace
    - wsl_v5

    # Complexity
    - gocyclo
    - gocognit
    - funlen

    # Security
    - gosec

    # Performance
    - prealloc

    # Maintainability
    - dupl
    - gocritic

  exclusions:
    rules:
      # lighten up tests
      - path: '_test\.go'
        linters:
          - gocyclo
          - dupl
          - funlen
          - lll
          - wsl_v5
          - errcheck
          - gocognit

      # skip generated protobufs
      - path: '.*\.pb\.go'
        linters:
          - revive
          - stylecheck

      # allow service registry configuration function to be longer
      - path: 'internal/app/container\.go'
        text: 'Function.*createServiceRegistrations.*is too long'
        linters:
          - funlen

      # common false positive in gosec
      - text: 'G404: Use of weak random number generator'
        linters:
          - gosec

      # allow dot-imports in main.go
      - path: 'main\.go'
        text: 'should not use dot imports'
        linters:
          - stylecheck

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (*os.File).Close
        - (*database/sql.Rows).Close
        - (*database/sql.Stmt).Close

    gocyclo:
      min-complexity: 15

    funlen:
      lines: 80
      statements: 40
      ignore-comments: true

    gocognit:
      min-complexity: 20

    lll:
      line-length: 120
      tab-width: 4

    unparam:
      check-exported: false

    revive:
      severity: warning
      rules:
        - name: exported
          severity: error
        - name: var-naming
          severity: error
        # - name: package-comments
        #   severity: warning

    govet:
      enable-all: true
      disable:
        - shadow

    staticcheck:
      checks: ["all"]

    gosec:
      severity: medium
      confidence: medium
      excludes:
        - G104

    dupl:
      threshold: 100

formatters:
  enable:
    - goimports
    - golines
  settings:
    goimports:
      local-prefixes:
        - github.com/terrpan/polly

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
