services:
  local:
    url: file:///bundle
    response_header_timeout_seconds: 5

bundles:
  compliance:
    service: local
    resource: bundle/
    persist: true
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 60

# When ready to use OCI, update the 'service' and 'url' fields accordingly.
# See https://www.openpolicyagent.org/docs/configuration/#oci-registries for details.
